### ISSUE TITLE
Plugin does NOT find K2 content (URGENT)

### ISSUE THREAD

**Issue by traubenliebe** [getk2/k2-links-for-jce#7] opened 2016-03-20 14:17 UTC
When I want to link to content in K2  no results show in the search.  Please advice. The latest versions for both JCE and plugin are installed. Important as I have a lot of content. 

Thank you in advance

Best regards

R

**Comment by kavadas** [comment] 2016-03-21 10:00
Duplicate of #6

**Closed as completed** 2016-10-21 15:12 UTC
Labels: duplicate, enhancement
